name: Build

on:
  push:
    pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: ESLint checks
        uses: stefanoeb/eslint-action@master

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.API_CLIENT_CODECOV_TOKEN}}
          flags: pr

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn build
